# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
osx_image: xcode8.3
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - PROJECT=SwinjectStoryboard.xcodeproj
  matrix:
## The iOS 8.1 simulator is commented out because it does not start. It looks a problem of the simulator.
## Uncomment the following line after the simulator problem is fixed.
#    - DESTINATION="OS=8.1,name=iPhone 4S" SCHEME="SwinjectStoryboard-iOS" SDK="$IOS_SDK" PLATFORM="iOS" POD_LINT="NO" ACTION="test"
    - DESTINATION="OS=9.3,name=iPhone 6" SCHEME="SwinjectStoryboard-iOS" SDK="iphonesimulator" PLATFORM="iOS" POD_LINT="NO" ACTION="test"
    - DESTINATION="OS=10.1,name=iPhone 6S Plus" SCHEME="SwinjectStoryboard-iOS" SDK="iphonesimulator" PLATFORM="iOS" POD_LINT="YES" ACTION="test"
    - DESTINATION="arch=x86_64" SCHEME="SwinjectStoryboard-OSX" SDK="$OSX_SDK" PLATFORM="macosx" POD_LINT="NO" ACTION="test"
    - DESTINATION="OS=9.2,name=Apple TV 1080p" SCHEME="SwinjectStoryboard-tvOS" SDK="appletvsimulator" PLATFORM="tvOS" POD_LINT="NO" ACTION="test"
    - DESTINATION="OS=10.0,name=Apple TV 1080p" SCHEME="SwinjectStoryboard-tvOS" SDK="appletvsimulator" PLATFORM="tvOS" POD_LINT="NO" ACTION="test"
before_install:
  - curl -L -O https://github.com/Carthage/Carthage/releases/download/0.23.0/Carthage.pkg
  - sudo installer -pkg Carthage.pkg -target /
  - rm Carthage.pkg
  - carthage bootstrap --platform iOS,macOS,tvOS --cache-builds
script:
  - set -o pipefail
  - xcodebuild -version
  - open -b com.apple.iphonesimulator # Workaround https://github.com/travis-ci/travis-ci/issues/3040
  - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" 
    -configuration Release ENABLE_TESTABILITY=YES ONLY_ACTIVE_ARCH=NO $ACTION | xcpretty
  - if [ $POD_LINT == "YES" ]; then
      pod repo update --silent;
      pod lib lint;
    fi
notifications:
  email:
    on_success: never
