# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
osx_image: xcode11
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - PROJECT=SwinjectStoryboard.xcodeproj  
matrix:
  include:
    - env: JOB="POD_LINT"
      osx_image: xcode11
      script:
        - bundle exec pod repo update
        - bundle exec pod lib lint
    - env: JOB="XCODE" DEST="OS=9.3,name=iPhone 6" SCHEME="SwinjectStoryboard-iOS" SDK="iphonesimulator" ACTION="test"
      osx_image: xcode11
    - env: JOB="XCODE" DEST="OS=10.3.1,name=iPhone 7 Plus" SCHEME="SwinjectStoryboard-iOS" SDK="iphonesimulator" ACTION="test"
      osx_image: xcode11
    - env: JOB="XCODE" DEST="OS=11.2,name=iPhone 8 Plus" SCHEME="SwinjectStoryboard-iOS" SDK="iphonesimulator" ACTION="test"
      osx_image: xcode11
    - env: JOB="XCODE" DEST="OS=12.2,name=iPhone X" SCHEME="SwinjectStoryboard-iOS" SDK="iphonesimulator" ACTION="test"
      osx_image: xcode11
    - env: JOB="XCODE" DEST="arch=x86_64" SCHEME="SwinjectStoryboard-OSX" SDK="macosx" ACTION="test"
      osx_image: xcode11
    - env: JOB="XCODE" DEST="arch=x86_64" SCHEME="SwinjectStoryboard-OSX" SDK="macosx" ACTION="test"
      osx_image: xcode11
    - env: JOB="XCODE" DEST="OS=9.2,name=Apple TV 1080p" SCHEME="SwinjectStoryboard-tvOS" SDK="appletvsimulator" ACTION="test"
      osx_image: xcode11
    - env: JOB="XCODE" DEST="OS=10.2,name=Apple TV 1080p" SCHEME="SwinjectStoryboard-tvOS" SDK="appletvsimulator" ACTION="test"
      osx_image: xcode11
    - env: JOB="XCODE" DEST="OS=11.0,name=Apple TV 4K" SCHEME="SwinjectStoryboard-tvOS" SDK="appletvsimulator" ACTION="test"
      osx_image: xcode11
before_install:
  - curl -L -O https://github.com/Carthage/Carthage/releases/download/0.28.0/Carthage.pkg
  - sudo installer -pkg Carthage.pkg -target /
  - rm Carthage.pkg
  - carthage bootstrap --platform iOS,macOS,tvOS --cache-builds
script:
  - set -o pipefail
  - xcodebuild "$ACTION" -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DEST" -configuration Release ENABLE_TESTABILITY=YES | xcpretty
notifications:
  email:
    on_success: never
    
cache:
  directories:
    - Carthage
